#+TITLE: Frankenstein (Mary Shelly, 1818)

I do not have to sing /Frankenstein/'s praises, its legacy speaks for
itself: very few novels have matched its lasting critical acclaim,
even fewer have been able to pioneer an emerging genre and almost none
have lodged themselves into the cultural imagination in the same way
/Frankenstein/ has. Although most people have never read (or maybe
aren't even aware of) the novel, pretty much everyone has a baseline
understanding of the story as well as a vivid mental image of
Frankenstein's creature.

Before reading the novel, I had never considered how its plot and
ideas had become enduring staples of the science fiction genre. Its
titular character and his creation are the first iterations of two of
the most popular SF tropes: the mad scientist and the creation born
out of his hubris. Its anxieties over researchers who view science as
an instrument to assert man's dominance over nature has only become
more relevant since the novel's release and has remained a core theme
in many science fiction stories. And of course, Frankenstein's
creature remains one of the most iconic and popular monsters in all of
fiction. To this day, if you watch any movie or read any story about
some scientific abomination, there is a good chance that Frankenstein
or his monster will be name checked at some point.

/Frankenstein/ has had such a stranglehold on popular culture not just
because it was the first story of its kind, but also because it was
exceptionally well written. Even with the massive deluge of stories
with similar themes and plots over the last two centuries, it remains
in a league of its own.
