name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
  - cron: "* 1 * * *"


jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-pages
    env:
      NOTES: ${{ secrets.NOTES }}
      CONFIG: ${{ secrets.CONFIG }}
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Test
        run: echo $NOTES

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Build the site
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
